# coding: utf-8

# flake8: noqa
"""
    Kimai 2 - API Docs

    JSON API for the Kimai 2 time-tracking software. Read more about its usage in the [API documentation](https://www.kimai.org/documentation/rest-api.html) and then download a [Swagger file](doc.json) for import e.g. in Postman. Be aware: it is not yet considered stable and BC breaks might happen, especially when using code generation. The order of JSON attributes is not guaranteed.   # noqa: E501

    OpenAPI spec version: 0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from pykimai.models.activity import Activity
from pykimai.models.activity_collection import ActivityCollection
from pykimai.models.activity_edit_form import ActivityEditForm
from pykimai.models.activity_entity import ActivityEntity
from pykimai.models.activity_expanded import ActivityExpanded
from pykimai.models.activity_meta import ActivityMeta
from pykimai.models.activity_rate import ActivityRate
from pykimai.models.activity_rate_form import ActivityRateForm
from pykimai.models.body import Body
from pykimai.models.body1 import Body1
from pykimai.models.body2 import Body2
from pykimai.models.body3 import Body3
from pykimai.models.body4 import Body4
from pykimai.models.customer import Customer
from pykimai.models.customer_collection import CustomerCollection
from pykimai.models.customer_edit_form import CustomerEditForm
from pykimai.models.customer_entity import CustomerEntity
from pykimai.models.customer_meta import CustomerMeta
from pykimai.models.customer_rate import CustomerRate
from pykimai.models.customer_rate_form import CustomerRateForm
from pykimai.models.i18n_config import I18nConfig
from pykimai.models.project import Project
from pykimai.models.project_collection import ProjectCollection
from pykimai.models.project_edit_form import ProjectEditForm
from pykimai.models.project_entity import ProjectEntity
from pykimai.models.project_expanded import ProjectExpanded
from pykimai.models.project_meta import ProjectMeta
from pykimai.models.project_rate import ProjectRate
from pykimai.models.project_rate_form import ProjectRateForm
from pykimai.models.tag_edit_form import TagEditForm
from pykimai.models.tag_entity import TagEntity
from pykimai.models.team import Team
from pykimai.models.team_collection import TeamCollection
from pykimai.models.team_edit_form import TeamEditForm
from pykimai.models.team_entity import TeamEntity
from pykimai.models.timesheet_collection import TimesheetCollection
from pykimai.models.timesheet_collection_expanded import TimesheetCollectionExpanded
from pykimai.models.timesheet_config import TimesheetConfig
from pykimai.models.timesheet_edit_form import TimesheetEditForm
from pykimai.models.timesheet_entity import TimesheetEntity
from pykimai.models.timesheet_meta import TimesheetMeta
from pykimai.models.user import User
from pykimai.models.user_collection import UserCollection
from pykimai.models.user_create_form import UserCreateForm
from pykimai.models.user_edit_form import UserEditForm
from pykimai.models.user_entity import UserEntity
from pykimai.models.version import Version
